Acme\DemoBundle\Model\Note:
  exclusion_policy: ALL
  xml_root_name: note
  properties:
    message:
      expose: true
      type: string
      groups: [standard, restapi]
    secret:
      expose: true
      type: string
      groups: [restapi]