Acme\TaskBundle\Model\Task:
  exclusion_policy: ALL
  xml_root_name: task
  properties:
    title:
      expose: true
      type: string
      groups: [list, show]
    description:
      expose: true
      type: string
      groups: [show]